"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { ArrowLeft } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

const policies = {
    "terms": {
        title: "Terms of Service",
        lastUpdated: "October 26, 2023",
        content: `
            <p>Welcome to Legalizd. These terms and conditions outline the rules and regulations for the use of our website and services.</p>
            <h3 class="font-semibold mt-4 mb-2">1. Acceptance of Terms</h3>
            <p>By accessing this platform, you accept these terms and conditions. Do not continue to use Legalizd if you do not agree to all of the terms and conditions stated on this page.</p>
            <h3 class="font-semibold mt-4 mb-2">2. User Responsibilities</h3>
            <p>You are responsible for ensuring that all information you provide is accurate and that your use of the platform is lawful. You must not use our platform for any illegal or unauthorized purpose.</p>
            <h3 class="font-semibold mt-4 mb-2">3. Intellectual Property</h3>
            <p>The Service and its original content, features, and functionality are and will remain the exclusive property of Legalizd and its licensors. Our trademarks may not be used in connection with any product or service without the prior written consent of Legalizd.</p>
            <h3 class="font-semibold mt-4 mb-2">4. Limitation of Liability</h3>
            <p>In no event shall Legalizd, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
            <h3 class="font-semibold mt-4 mb-2">5. Governing Law</h3>
            <p>These Terms shall be governed and construed in accordance with the laws of India, without regard to its conflict of law provisions.</p>
        `
    },
    "privacy": {
        title: "Privacy Policy",
        lastUpdated: "October 26, 2023",
        content: `
            <p>Your privacy is important to us. It is Legalizd's policy to respect your privacy regarding any information we may collect from you across our website.</p>
            <h3 class="font-semibold mt-4 mb-2">1. Information We Collect</h3>
            <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We may collect information like your name, email address, company details, and usage data.</p>
            <h3 class="font-semibold mt-4 mb-2">2. How We Use Your Data</h3>
            <p>We use the collected data to provide and maintain our Service, to notify you about changes to our Service, to allow you to participate in interactive features of our Service when you choose to do so, and to provide customer support.</p>
            <h3 class="font-semibold mt-4 mb-2">3. Data Security</h3>
            <p>We take the security of your data seriously and use appropriate technical and organizational measures to protect it against unauthorized or unlawful processing and against accidental loss, destruction, or damage.</p>
            <h3 class="font-semibold mt-4 mb-2">4. User Rights</h3>
            <p>You have the right to access, update or to delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section.</p>
        `
    },
    "disclaimer": {
        title: "AI Disclaimer",
        lastUpdated: "October 26, 2023",
        content: `
            <p>The features and information generated by the Artificial Intelligence (AI) on the Legalizd platform are provided for informational purposes only.</p>
            <h3 class="font-semibold mt-4 mb-2">1. Not Professional Advice</h3>
            <p>The content generated by our AI is not intended to be a substitute for professional legal, financial, or tax advice. Always seek the advice of a qualified professional with any questions you may have regarding a legal or financial matter.</p>
            <h3 class="font-semibold mt-4 mb-2">2. No Guarantees</h3>
            <p>While we strive to provide accurate and up-to-date information, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the AI-generated content. Any reliance you place on such information is therefore strictly at your own risk.</p>
            <h3 class="font-semibold mt-4 mb-2">3. Limitation of Liability</h3>
            <p>Legalizd disclaims all liability for any errors or omissions in the content provided by the AI and for any actions taken in reliance on that content.</p>
        `
    }
};

type PolicyKey = keyof typeof policies;

export default function LegalPoliciesPage() {
    const searchParams = useSearchParams();
    const defaultTab = (searchParams.get('tab') as PolicyKey) || 'terms';

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-4">
                <Button variant="outline" size="icon" asChild>
                    <Link href="/dashboard"><ArrowLeft/></Link>
                </Button>
                <div>
                    <h1 className="text-3xl font-bold tracking-tight font-headline">Legal & Policies</h1>
                    <p className="text-muted-foreground">Our terms of service, privacy policy, and other legal documents.</p>
                </div>
            </div>
            
            <Card className="interactive-lift">
                <CardContent className="p-2 md:p-4">
                    <Accordion type="single" collapsible defaultValue={defaultTab} className="w-full">
                        {Object.entries(policies).map(([key, policy]) => (
                            <AccordionItem value={key} key={key}>
                                <AccordionTrigger className="p-4 text-lg font-semibold hover:no-underline">{policy.title}</AccordionTrigger>
                                <AccordionContent className="px-4">
                                    <div className="prose dark:prose-invert max-w-none border-t pt-4">
                                        <p className="text-sm text-muted-foreground">Last updated: {policy.lastUpdated}</p>
                                        <div dangerouslySetInnerHTML={{ __html: policy.content }} />
                                    </div>
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </CardContent>
            </Card>
        </div>
    );
}
