
import type { Clause } from './types';

export const allClauses: Clause[] = [
  // Company Formation / Governance Clauses
  {
    id: 'gov_1',
    title: 'Registered Office Clause',
    category: 'Company Formation',
    content: 'The registered office of the company will be situated in the State of [State], India.',
    description: 'Specifies the legal address of the company.',
    useCase: 'Required during incorporation and for ROC filings.',
    relevantSection: 'Section 12, Companies Act, 2013',
    editableFields: ['[State]'],
  },
  {
    id: 'gov_2',
    title: 'Main Object Clause',
    category: 'Governance',
    content: 'The main objects to be pursued by the company on its incorporation are: [Main Business Activity].',
    description: 'Declares the primary business activities.',
    useCase: 'Included in MOA to define scope of operations.',
    relevantSection: 'Section 4(1)(c), Companies Act, 2013',
    editableFields: ['[Main Business Activity]'],
  },
  {
    id: 'gov_3',
    title: 'Liability Clause (Limited by Shares)',
    category: 'Legal Structure',
    content: 'The liability of the members is limited to the amount, if any, unpaid on the shares respectively held by them.',
    description: 'Limits the liability of shareholders.',
    useCase: 'Essential for private/public companies limited by shares.',
    relevantSection: 'Section 4(1)(d), Companies Act, 2013',
    editableFields: [],
  },
  {
    id: 'gov_4',
    title: 'Share Capital Clause',
    category: 'Governance',
    content: 'The authorized share capital of the company is [Amount] Rupees, divided into [Number of Shares] equity shares of [Nominal Value] Rupees each.',
    description: 'Details authorized and paid-up share capital.',
    useCase: 'Required in MOA and ROC filings.',
    relevantSection: 'Section 43 & 44, Companies Act, 2013',
    editableFields: ['[Amount]', '[Number of Shares]', '[Nominal Value]'],
  },
  {
    id: 'gov_5',
    title: 'Board Meeting Notice Clause',
    category: 'Governance',
    content: 'A meeting of the Board of Directors shall be held by giving not less than [Notice Period] days notice in writing to every director at his address registered with the company.',
    description: 'Specifies procedure and notice period for board meetings.',
    useCase: 'Board communication protocols.',
    relevantSection: 'Section 173, Companies Act, 2013',
    editableFields: ['[Notice Period]'],
  },
  {
    id: 'gov_6',
    title: 'Quorum Requirement Clause',
    category: 'Meetings',
    content: 'The quorum for a meeting of the Board of Directors shall be one-third of its total strength or two directors, whichever is higher.',
    description: 'Sets the minimum number of members required for a meeting.',
    useCase: 'Prevents decisions without representation.',
    relevantSection: 'Section 174, Companies Act, 2013',
    editableFields: [],
  },
  {
    id: 'gov_7',
    title: 'Voting Rights Clause',
    category: 'Corporate Governance',
    content: 'Subject to any rights or restrictions for the time being attached to any class or classes of shares, on a show of hands every member present in person shall have one vote, and upon a poll each member shall have one vote for each share of which he is the holder.',
    description: 'Details voting power per shareholder/class.',
    useCase: 'During AGMs, resolutions.',
    relevantSection: 'Section 47, Companies Act, 2013',
    editableFields: [],
  },
  {
    id: 'gov_8',
    title: 'Indemnity Clause for Directors',
    category: 'Risk & Legal',
    content: 'The company shall indemnify every director for any liabilities incurred by him in defending any proceedings, whether civil or criminal, in which judgment is given in his favor or in which he is acquitted or in connection with any application under section 463 in which relief is granted to him by the Court.',
    description: 'Protects directors from liabilities for acts done in good faith.',
    useCase: 'In director agreements.',
    relevantSection: 'Section 197(13), Companies Act, 2013',
    editableFields: [],
  },

  // Employment & HR Clauses
  {
    id: 'hr_1',
    title: 'Non-Compete Clause',
    category: 'Employment',
    content: 'For a period of [Time Period] after the termination of employment, the Employee shall not, directly or indirectly, engage in, or have any ownership interest in, any business that competes with the Company within [Geography].',
    description: 'Restricts employee from working with competitors.',
    useCase: 'Included in employment contracts.',
    relevantSection: 'Enforced under Contract Act, 1872 – Section 27 (subject to reasonable limits)',
    editableFields: ['[Time Period]', '[Geography]'],
  },
  {
    id: 'hr_2',
    title: 'Non-Solicitation Clause',
    category: 'HR Compliance',
    content: 'During the term of employment and for [Duration] thereafter, the Employee shall not solicit or attempt to solicit any business from any of the Company’s clients or customers, or entice away any employee of the Company.',
    description: 'Prevents employees from soliciting clients or team post-exit.',
    useCase: 'Exit agreements.',
    relevantSection: 'Contract Act, 1872 – Common law principle',
    editableFields: ['[Duration]'],
  },
  {
    id: 'hr_3',
    title: 'Termination Clause',
    category: 'Employment',
    content: 'This agreement may be terminated by either party by giving [Notice Period] in writing. The Company reserves the right to terminate this agreement without notice in case of gross misconduct by the Employee.',
    description: 'Governs termination notice, conditions, and grounds.',
    useCase: 'Employment agreement.',
    relevantSection: 'Labour Laws + Shops & Establishments Act',
    editableFields: ['[Notice Period]'],
  },
  {
    id: 'hr_4',
    title: 'Confidentiality Clause',
    category: 'Legal / HR',
    content: 'The Employee shall not, during or after the term of employment, disclose any confidential information, including but not limited to trade secrets, client lists, and financial data, to any third party without the prior written consent of the Company.',
    description: 'Protects business information.',
    useCase: 'Employment, NDA, vendor contracts.',
    relevantSection: 'Contract Act, 1872',
    editableFields: [],
  },
  {
    id: 'hr_5',
    title: 'ESOP Vesting Clause',
    category: 'Startup HR',
    content: 'The stock options granted shall vest over a period of [Vesting Years] years, with a one-year cliff. Following the cliff, the remaining options shall vest on a monthly/quarterly basis.',
    description: 'Specifies vesting schedule of ESOPs.',
    useCase: 'ESOP policy docs.',
    relevantSection: 'Rule 12, Companies (Share Capital and Debentures) Rules, 2014',
    editableFields: ['[Vesting Years]'],
  },

  // Financial & Audit Clauses
  {
    id: 'fin_1',
    title: 'Statutory Auditor Appointment Clause',
    category: 'Financial Compliance',
    content: 'RESOLVED THAT pursuant to the provisions of Section 139 of the Companies Act, 2013, [Auditor Name], Chartered Accountants, be and are hereby appointed as Statutory Auditors of the Company to hold office from the conclusion of this Annual General Meeting until the conclusion of the sixth consecutive Annual General Meeting.',
    description: 'Outlines the appointment of statutory auditors by the board or shareholders.',
    useCase: 'Annual general meetings, ROC filings.',
    relevantSection: 'Section 139, Companies Act, 2013',
    editableFields: ['[Auditor Name]'],
  },
  {
    id: 'fin_2',
    title: 'Books of Accounts Maintenance Clause',
    category: 'Accounting',
    content: 'The books of account & other relevant books & papers of the company shall be kept at the Registered office of the company at [Office Location]. The company shall maintain its accounts on an accrual basis and according to the double entry system of accounting.',
    description: 'Mandates accurate maintenance of books of accounts.',
    useCase: 'Financial records, audits.',
    relevantSection: 'Section 128, Companies Act, 2013',
    editableFields: ['[Office Location]'],
  },
  {
    id: 'fin_3',
    title: 'Dividend Declaration Clause',
    category: 'Finance & Compliance',
    content: 'A dividend at the rate of [Dividend Rate]% on the paid-up equity share capital of the company is hereby declared for the financial year ended March 31, [Year], and the same be paid to those shareholders whose names appear on the Register of Members as on [Record Date].',
    description: 'Lays down rules for declaring dividends.',
    useCase: 'AGM resolutions, investor communication.',
    relevantSection: 'Section 123, Companies Act, 2013',
    editableFields: ['[Dividend Rate]', '[Year]', '[Record Date]'],
  },
  {
    id: 'fin_4',
    title: 'Tax Deducted at Source (TDS) Clause',
    category: 'Tax Compliance',
    content: 'The Company shall deduct Tax at Source (TDS) on all applicable payments as per the prevailing rates prescribed under the Income Tax Act, 1961, and shall issue the corresponding TDS certificate to the deductee within the stipulated time.',
    description: 'Ensures deduction and deposit of TDS on applicable transactions.',
    useCase: 'Vendor payments, salaries, rent, etc.',
    relevantSection: 'Section 194 series, Income Tax Act, 1961',
    editableFields: [],
  },

  // Agreements & Contracts Clauses
  {
    id: 'agr_1',
    title: 'Force Majeure Clause',
    category: 'Commercial Contracts',
    content: 'Neither party shall be liable for any failure or delay in performance under this Agreement to the extent said failures or delays are proximately caused by causes beyond that party\'s reasonable control and occurring without its fault or negligence, including, without limitation, acts of God, acts of government, fires, floods, or strikes.',
    description: 'Protects parties from liability for unforeseen events.',
    useCase: 'Vendor, SaaS, supply chain, or service contracts.',
    relevantSection: 'Contract Act, 1872 – Common law interpretation',
    editableFields: [],
  },
  {
    id: 'agr_2',
    title: 'Jurisdiction Clause',
    category: 'Legal Dispute Resolution',
    content: 'Any dispute, controversy or claims arising out of or relating to this Agreement or the breach, termination or invalidity thereof, shall be settled by the courts of [City], [State], which shall have exclusive jurisdiction.',
    description: 'Specifies the court or city where disputes will be resolved.',
    useCase: 'All standard contracts.',
    relevantSection: 'Civil Procedure Code, 1908',
    editableFields: ['[City]', '[State]'],
  },
  {
    id: 'agr_3',
    title: 'Governing Law Clause',
    category: 'Contract Law',
    content: 'This Agreement shall be governed by and construed in accordance with the laws of [Country/State], without regard to its conflict of law principles.',
    description: 'States which country/state’s laws will apply.',
    useCase: 'Cross-border or multi-state agreements.',
    relevantSection: 'Contract Act, 1872',
    editableFields: ['[Country/State]'],
  },
  {
    id: 'agr_4',
    title: 'Arbitration Clause',
    category: 'Dispute Resolution',
    content: 'Any dispute arising out of or in connection with this contract, including any question regarding its existence, validity or termination, shall be referred to and finally resolved by arbitration administered by a sole arbitrator appointed in accordance with the Arbitration and Conciliation Act, 1996. The seat of the arbitration shall be [City].',
    description: 'Refers disputes to an arbitrator instead of courts.',
    useCase: 'Vendor, founder, investor agreements.',
    relevantSection: 'Arbitration & Conciliation Act, 1996',
    editableFields: ['[City]'],
  },

  // Startup & Fundraising Clauses
  {
    id: 'fund_1',
    title: 'Pre-Emptive Rights Clause',
    category: 'Equity Protection',
    content: 'If the Company proposes to issue any new Equity Securities, each Major Investor shall have a right of first refusal to purchase its pro-rata share of such New Securities.',
    description: 'Gives existing investors the right to buy new shares before outsiders.',
    useCase: 'Shareholders\' Agreement (SHA).',
    relevantSection: 'Companies Act, 2013 – Section 62',
    editableFields: [],
  },
  {
    id: 'fund_2',
    title: 'Tag-Along Rights Clause',
    category: 'Minority Investor Protection',
    content: 'In the event that any Selling Shareholder proposes to transfer Shares to a third party, each other Shareholder shall have the right to participate in such sale on a pro-rata basis and on the same terms and conditions as the Selling Shareholder.',
    description: 'Allows minority investors to sell their stake if majority does.',
    useCase: 'SHA, VC term sheets.',
    relevantSection: 'Contractual right; not under Companies Act',
    editableFields: [],
  },
  {
    id: 'fund_3',
    title: 'Drag-Along Rights Clause',
    category: 'Majority Exit Rights',
    content: 'If Shareholders holding more than [Percentage]% of the shares agree to sell their shares to a third party, such Shareholders shall have the right to require all other Shareholders to sell their shares to such third party on the same terms and conditions.',
    description: 'Allows majority shareholders to force minority to sell during exit.',
    useCase: 'Venture rounds, acquisition terms.',
    relevantSection: 'SHA-based; recognized in corporate practice',
    editableFields: ['[Percentage]%'],
  },
  {
    id: 'fund_4',
    title: 'Liquidation Preference Clause',
    category: 'Investment Rights',
    content: 'In the event of any liquidation, dissolution or winding up of the Company, the holders of Series A Preferred Shares shall be entitled to receive, prior and in preference to any distribution of any of the assets of the Company to the holders of Common Shares, an amount per share equal to [Preference Multiple] times the Original Issue Price for such share.',
    description: 'Defines payout order in case of liquidation or sale.',
    useCase: 'VC investments.',
    relevantSection: 'SHA clause; governed under company agreements',
    editableFields: ['[Preference Multiple]'],
  },
  {
    id: 'fund_5',
    title: 'Founder Lock-in Clause',
    category: 'Founder Obligation',
    content: 'The Founders agree not to sell, transfer, or otherwise dispose of any of their shares in the Company for a period of [Lock-in Duration] from the date of this Agreement, without the prior written consent of the Investors.',
    description: 'Restricts founders from exiting or transferring shares early.',
    useCase: 'Term sheet, SHA.',
    relevantSection: 'Contractual',
    editableFields: ['[Lock-in Duration]'],
  },
];
